name: koberorder
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_slider_drawer: ^2.1.1
  font_awesome_flutter: ^10.2.1
  get: 4.6.5
  http: ^0.13.5
  line_icons: ^2.0.1
  lottie: ^1.4.3
  sliding_up_panel: ^2.0.0+1
  vertical_scrollable_tabview: ^0.0.7
  vertical_tabs_flutter: ^1.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/brand/
    - assets/lottie/
